---
# timezone
- name: set timezone
  copy: content={{ubuntu_timezone}} dest=/etc/timezone mode=0644 force=yes
- name: set localtime
  copy: src=/usr/share/zoneinfo/{{ubuntu_timezone}} dest=/etc/localtime mode=644 force=yes

# system packages
- name: use amazons package archive
  replace: dest=/etc/apt/sources.list regexp="http://archive.ubuntu.com/ubuntu" replace={{ubuntu_package_archive}}
  when: ubuntu_package_archive != ""
- name: install python-software-properties
  apt: name=python-software-properties state=latest update_cache=yes cache_valid_time=3600
- name: add git's apt repository
  apt_repository: repo="ppa:git-core/ppa" state=present
- name: install packages
  apt: pkg={{item}} update_cache=yes cache_valid_time=3600 state=latest
  with_items:
  - vim
  - emacs
  - git
  - unattended-upgrades

# enable automatic upgrades
- name: update package lists
  lineinfile: dest=/etc/apt/apt.conf.d/50unattended-upgrades line='APT::Periodic::Update-Package-Lists "1";' state=present
- name: unattended upgrade
  lineinfile: dest=/etc/apt/apt.conf.d/50unattended-upgrades line='APT::Periodic::Unattended-Upgrade "1";' state=present

# set application_environment
- name: update /etc/application_environment
  template: src=application_environment dest=/etc/application_environment